apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacturing-app
  labels:
    app: manufacturing
spec:
  replicas: 1  # Keeping it at 1 to stay within t3.micro RAM limits
  selector:
    matchLabels:
      app: manufacturing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: manufacturing
    spec:
      containers:
      - name: flask-app
        image: chitrakjiyal/devops_app:latest
        ports:
        - containerPort: 8501
        # PASTE THE BLOCK BELOW:
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: API_KEY
  template:
    metadata:
      labels:
        app: manufacturing
    spec:
      containers:
      - name: flask-app
        image: chitrakjiyal/devops_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        # Resource constraints to protect your Free Tier EC2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
